CREATE TABLE "LOGINTYPE"
(
  "LOGINTYPEID" integer NOT NULL,
  "LABEL" varchar(128) NOT NULL,
  "DESCRIPTION" varchar(128) NOT NULL,
  "ICON" varchar(128) NOT NULL,
  "HELP" varchar(128) NOT NULL,
  "ISACTIVE" boolean NOT NULL DEFAULT true,
  "VERSION" integer NOT NULL DEFAULT 1,
  "CREATEDBY" varchar(128) NOT NULL,
  "CREATEDTIME" timestamp with time zone NOT NULL,
  CONSTRAINT "LOGINTYPEID_PK" PRIMARY KEY ("LOGINTYPEID")
);
