	CREATE TABLE "APPSTATE"
(
  "APPSTATEUUID" varchar(128) NOT NULL,
  "APPSESSIONID" varchar(128) NOT NULL,
  "TABDATA" varchar(10240) NOT NULL,
  "TABID" integer NOT NULL,
  "ISTABACTIVE" boolean NOT NULL,
  "LATITUDE" double precision NOT NULL,
  "LONGITUDE" double precision NOT NULL,
  "LOGINUUID" varchar(128) NOT NULL,
  "USERAGENT" varchar(128) NOT NULL,
  "MTEID" varchar(128) NOT NULL,
  "ISACTIVE" boolean NOT NULL DEFAULT true,
  "VERSION" integer NOT NULL DEFAULT 1,
  "CREATEDBY" varchar(128) NOT NULL,
  "CREATEDTIME" timestamp with time zone NOT NULL,
  "UPDATEDBY" varchar(128) NOT NULL,
  "UPDATEDTIME" timestamp with time zone NOT NULL,
  CONSTRAINT "APPSTATEUUID_PK" PRIMARY KEY ("APPSTATEUUID"),
  CONSTRAINT "APPSTATE_LOGINUUID_fkey" FOREIGN KEY ("LOGINUUID")
      REFERENCES "AUTHSCHEMA" ("LOGINUUID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "APPSTATE_APPSESSIONID_fkey" FOREIGN KEY ("APPSESSIONID")
      REFERENCES "APPSESSION" ("APPSESSIONID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

