CREATE TABLE "LOGINHISTORY" 
(
  "LOGINHISTORYUUID" varchar(128) NOT NULL,
  "MTEID" varchar(128) NOT NULL,
  "USERUUID" varchar(128) NOT NULL,
  "APPSESSIONID" varchar(128) NOT NULL,
  "LOGINTYPEID" integer NOT NULL,
  "LOGINFORMFACTORID" integer NOT NULL,
  "IPADDRESS" varchar(128) NOT NULL,
  "BROWSER" text NOT NULL,
  "USERAGENT" text NOT NULL,
  "LATITUDE" double precision,
  "LONGITUDE" double precision,
  "ISACTIVE" boolean NOT NULL DEFAULT true,
  "VERSION" integer NOT NULL DEFAULT 1,
  "CREATEDBY" varchar(128) NOT NULL,
  "CREATEDTIME" timestamp with time zone NOT NULL,
  "UPDATEDBY" varchar(128) NOT NULL,
  "UPDATEDTIME" timestamp with time zone NOT NULL,
  CONSTRAINT "LOGINHISTORY_PK" PRIMARY KEY ("LOGINHISTORYUUID"),
  CONSTRAINT "LOGINHISTORY_LOGINFORMFACTORID_fkey" FOREIGN KEY ("LOGINFORMFACTORID")
      REFERENCES "LOGINFORMFACTOR" ("LOGINFORMFACTORID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "LOGINHISTORY_LOGINTYPEID_fkey" FOREIGN KEY ("LOGINTYPEID")
      REFERENCES "LOGINTYPE" ("LOGINTYPEID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "LOGINHISTORY_USERUUID_fkey" FOREIGN KEY ("USERUUID")
      REFERENCES "USERSCHEMA" ("USERUUID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "LOGINHISTORY_APPSESSIONID_fkey" FOREIGN KEY ("APPSESSIONID")
      REFERENCES "APPSESSION" ("APPSESSIONID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);
